# Use root/example as user/password credentials
version: '3.1'

services:

  wireless_location_mongo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wireless_location_database
    restart: always
    expose:
      - "28910"
    ports:
      - "28910:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    user: "1000:1000"